### ISSUE TITLE
`coef()` results was changed

### ISSUE THREAD

**Issue by mkojima123** [quadbio/Pando#46]
Hi, Thank you for this package.
I using pando in my own data.
https://quadbio.github.io/Pando/articles/getting_started.html
When I use `subset` from Signac, `coef()` result was different.
https://stuartlab.org/signac/articles/pbmc_vignette

Strangely enough, when I increase `nCount_peaks > 3000`, the number of rows in the `coef()` result increases, even though the number of cells is decreasing.

Is there a reason why this ? thank you.

**Comment by joschif** [comment]
Hi @mkojima123, unfortunately I don't fully know and also can't really control how Seurats `subset` function interacts with the `SeuratPlus` object that Pando creates. I tried to make the object compatible with most Seurat functions, at least the ones that don't change the shape of the arrays. What you describe seems quite strange, and it leads me to believe that `subset` might not be fully compatible with Pando and I would avoid using it. As a workaround you can just save individual networks created by pando and add then back in after the subset. But anyway, the network would not by really valid for the subsetted object anymore, since inference on it would result in in different coefficients.

**Comment by mkojima123** [comment]
Thank you. I'm sorry for the late reply.
I understood that it is better not use `subset`.
Thank you for the information.
